// License: LICENSE.TXT

using System;
using System.Collections.Generic;
using System.Text;

namespace Pencil.Gaming {
    /// <summary>
    /// Indicates that this function is generated automatically by a tool.
    /// </summary>
    public sealed class AutoGeneratedAttribute : Attribute {
        /// <summary>
        /// Specifies the category of this OpenGL function.
        /// </summary>
        public string Category;

        /// <summary>
        /// Specifies the version of this OpenGL function.
        /// </summary>
        public string Version;

        /// <summary>
        /// Specifies the entry point of the OpenGL function.
        /// </summary>
        public string EntryPoint;

        /// <summary>
        /// Constructs a new AutoGeneratedAttribute instance.
        /// </summary>
        public AutoGeneratedAttribute() {
        }
    }
}
